stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
variables:
  APP_VERSION: $CI_PIPELINE_ID
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:current-alpine3.18
  script:
    - npm install
    - npm run build
    - npm run test
    - echo $APP_VERSION
  artifacts:
    paths:
      - build

build docker image:
  stage: build
  image: docker:24.0.4
  services:
    - docker: 24.0.4-dind
  script: 
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$CI_JOB_ID .
    - docker image ls
    
