stages:          # List of stages for jobs, and their order of execution
  - build
  - push-image

variables:
  APP_VERSION: $CI_PIPELINE_ID
  DOCKER_REGISTRY: 100525915128.dkr.ecr.us-east-2.amazonaws.com
  APP_NAME: andersen-task-stage
  CONTAINER_TEST_IMAGE: $DOCKER_REGISTRY/$APP_NAME:$APP_VERSION
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY/$APP_NAME:latest

build-job:      
  stage: build
  image: node:current-alpine3.18
  script:
    - npm install
    - npm run build
    - echo $APP_VERSION
  artifacts:
    paths:
      - build
      - node_modules

docker-push-image:
  stage: push-image
  image: 
    name: docker:24.0.4
  services:
    - docker:24.0.4-dind
  before_script:
    - apk add python3 py3-pip
    - pip3 install --no-cache-dir awscli
  script:
    - docker build -t $CONTAINER_TEST_IMAGE  .
    - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
