stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
variables:
  APP_VERSION: $CI_PIPELINE_ID
build-job:      
  stage: build
  image: node:current-alpine3.18
  script:
    - npm install
    - npm run build
    - echo $APP_VERSION
  artifacts:
    paths:
      - build

docker-image:
  stage: build
  image: docker:24.0.4
  services:
    - docker:24.0.4-dind
  script: 
    - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$CI_JOB_ID .
    - docker image ls
    
