apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEzQjBaWGN4UUdkdFlXbHNMbU52YlRwTk5HRXhZV3MwTnpsaE9URT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson